version: '2.0'

services:

  api:
    container_name: choicemd_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 5000:5000
    environment:
      POSTGRES_DATABASE_HOST: choicemd_db
      POSTGRES_DATABASE: choicemd
      POSTGRES_USER: choicemd
      POSTGRES_PASSWORD: test123
  
  database:
    image: mdillon/postgis
    container_name: choicemd_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: choicemd
      POSTGRES_USER: choicemd
      POSTGRES_PASSWORD: test123
    ports:
      - 5432:5432